// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.27.1

package net.heydel.protobuf;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pv_teil_2.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string to = 1;</code>
   * @return Whether the to field is set.
   */
  boolean hasTo();
  /**
   * <code>required string to = 1;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <code>required string to = 1;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>required string content = 2;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>required string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>required string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
