// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.27.1

package net.heydel.protobuf;

public interface CodeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pv_teil_2.CodeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 code = 1;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 1;</code>
   * @return The code.
   */
  int getCode();
}
