// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.27.1

package net.heydel.protobuf;

public interface LoginMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pv_teil_2.LoginMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>required string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>required string password = 2;</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>required string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>required string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
