// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.27.1

package net.heydel.protobuf;

public final class Message {
  private Message() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Message.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pv_teil_2_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pv_teil_2_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pv_teil_2_LoginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pv_teil_2_LoginMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pv_teil_2_CodeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pv_teil_2_CodeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pv_teil_2_MessageWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pv_teil_2_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\tpv_teil_2\"*\n\013ChatMessage\022\n" +
      "\n\002to\030\001 \002(\t\022\017\n\007content\030\002 \002(\t\"2\n\014LoginMess" +
      "age\022\020\n\010username\030\001 \002(\t\022\020\n\010password\030\002 \002(\t\"" +
      "\033\n\013CodeMessage\022\014\n\004code\030\001 \002(\005\"\262\001\n\016Message" +
      "Wrapper\022.\n\014chat_message\030\001 \001(\0132\026.pv_teil_" +
      "2.ChatMessageH\000\0220\n\rlogin_message\030\002 \001(\0132\027" +
      ".pv_teil_2.LoginMessageH\000\022.\n\014code_messag" +
      "e\030\003 \001(\0132\026.pv_teil_2.CodeMessageH\000B\016\n\014mes" +
      "sage_typeB \n\023net.heydel.protobufB\007Messag" +
      "eP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pv_teil_2_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pv_teil_2_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pv_teil_2_ChatMessage_descriptor,
        new java.lang.String[] { "To", "Content", });
    internal_static_pv_teil_2_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pv_teil_2_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pv_teil_2_LoginMessage_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_pv_teil_2_CodeMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pv_teil_2_CodeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pv_teil_2_CodeMessage_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_pv_teil_2_MessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pv_teil_2_MessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pv_teil_2_MessageWrapper_descriptor,
        new java.lang.String[] { "ChatMessage", "LoginMessage", "CodeMessage", "MessageType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
